# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'root@jler.vip:wangwenzhen/AutoBaseSpec.git'

target 'BGAlertViewDemo' do

 pod 'BeautyKit', :git => 'http://gogs.jler.vip/wangwenzhen/BGAlertView'
 pod 'Masonry’,'~> 1.1.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
     end
    end
  end
